//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.7.2+fd5b8de
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Oppa13.ContentModels
{
	/// <summary>Brokeris</summary>
	[PublishedModel("brokeris")]
	public partial class Brokeris : PublishedContentModel, IPuslapioNavigacijosPasirinkimai, IPuslapioSeopasirinkimai
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const string ModelTypeAlias = "brokeris";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Brokeris, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Brokeris(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Aprašymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymas")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Aprasymas => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "aprasymas");

		///<summary>
		/// Aprašymas-EN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymasEN")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AprasymasEN => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "aprasymasEN");

		///<summary>
		/// Aprašymas-RU
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymasRU")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AprasymasRU => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "aprasymasRU");

		///<summary>
		/// El. paštas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("elPastas")]
		public virtual string ElPastas => this.Value<string>(_publishedValueFallback, "elPastas");

		///<summary>
		/// Facebook profilis
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("facebookProfilis")]
		public virtual string FacebookProfilis => this.Value<string>(_publishedValueFallback, "facebookProfilis");

		///<summary>
		/// Instagram profilis
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("instagramProfilis")]
		public virtual string InstagramProfilis => this.Value<string>(_publishedValueFallback, "instagramProfilis");

		///<summary>
		/// Kalbos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("kalbos")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Kalbos => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "kalbos");

		///<summary>
		/// LinkedIn profilis
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkedInProfilis")]
		public virtual string LinkedInProfilis => this.Value<string>(_publishedValueFallback, "linkedInProfilis");

		///<summary>
		/// Media aplankas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaAplankas")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent MediaAplankas => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "mediaAplankas");

		///<summary>
		/// Nuotrauka
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuotrauka")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent Nuotrauka => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "nuotrauka");

		///<summary>
		/// Pareigos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pareigos")]
		public virtual string Pareigos => this.Value<string>(_publishedValueFallback, "pareigos");

		///<summary>
		/// Pareigos-EN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pareigosEN")]
		public virtual string PareigosEN => this.Value<string>(_publishedValueFallback, "pareigosEN");

		///<summary>
		/// Pareigos-RU
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pareigosRU")]
		public virtual string PareigosRU => this.Value<string>(_publishedValueFallback, "pareigosRU");

		///<summary>
		/// Pavardė
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pavarde")]
		public virtual string Pavarde => this.Value<string>(_publishedValueFallback, "pavarde");

		///<summary>
		/// Reitingas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("reitingas")]
		public virtual int Reitingas => this.Value<int>(_publishedValueFallback, "reitingas");

		///<summary>
		/// Sumažint nuotrauku dydį
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("sumazintNuotraukuDydi")]
		public virtual bool SumazintNuotraukuDydi => this.Value<bool>(_publishedValueFallback, "sumazintNuotraukuDydi");

		///<summary>
		/// Telefonas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("telefonas")]
		public virtual string Telefonas => this.Value<string>(_publishedValueFallback, "telefonas");

		///<summary>
		/// Trumpas aprašymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trumpasAprasymas")]
		public virtual string TrumpasAprasymas => this.Value<string>(_publishedValueFallback, "trumpasAprasymas");

		///<summary>
		/// Trumpas aprašymas-EN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trumpasAprasymasEN")]
		public virtual string TrumpasAprasymasEN => this.Value<string>(_publishedValueFallback, "trumpasAprasymasEN");

		///<summary>
		/// Trumpas aprašymas-RU
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("trumpasAprasymasRU")]
		public virtual string TrumpasAprasymasRU => this.Value<string>(_publishedValueFallback, "trumpasAprasymasRU");

		///<summary>
		/// Twitter profilis
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twitterProfilis")]
		public virtual string TwitterProfilis => this.Value<string>(_publishedValueFallback, "twitterProfilis");

		///<summary>
		/// Vardas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vardas")]
		public virtual string Vardas => this.Value<string>(_publishedValueFallback, "vardas");

		///<summary>
		/// Slėpti meniu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Oppa13.ContentModels.PuslapioNavigacijosPasirinkimai.GetUmbracoNaviHide(this, _publishedValueFallback);

		///<summary>
		/// Meta antraštė
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaAntraste")]
		public virtual string MetaAntraste => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaAntraste(this, _publishedValueFallback);

		///<summary>
		/// Meta aprašymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaAprasymas")]
		public virtual string MetaAprasymas => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaAprasymas(this, _publishedValueFallback);

		///<summary>
		/// Meta nuotrauka
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaNuotrauka")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent MetaNuotrauka => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaNuotrauka(this, _publishedValueFallback);

		///<summary>
		/// Meta ranktažodžiai
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaRanktazodziai")]
		public virtual string MetaRanktazodziai => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaRanktazodziai(this, _publishedValueFallback);
	}
}
