//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.7.2+fd5b8de
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Oppa13.ContentModels
{
	/// <summary>Butas</summary>
	[PublishedModel("butas")]
	public partial class Butas : PublishedContentModel, IApsaugosPasirinkimai, IButoBendriPasirinkimai, IEnergijosSuvartojimoPasirinkimai, IObjektoAprasymoPasirinkimai, IObjektoTipoPasirinkimai, IObjektoXmlPasirinkimai, IPapildomosIrangosPasirinkimai, IPapildomuPatalpuPasirinkimai, IPuslapioSeopasirinkimai, ISildymoPasirinkimai, IVietosPasirinkimai, IYpatybiuPasirinkimai
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const string ModelTypeAlias = "butas";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Butas, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Butas(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Apsauga
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("apsauga")]
		public virtual global::System.Collections.Generic.List<string> Apsauga => global::Oppa13.ContentModels.ApsaugosPasirinkimai.GetApsauga(this, _publishedValueFallback);

		///<summary>
		/// Aukštas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("aukstas")]
		public virtual int Aukstas => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetAukstas(this, _publishedValueFallback);

		///<summary>
		/// Buto numeris
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("butoNumeris")]
		public virtual string ButoNumeris => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetButoNumeris(this, _publishedValueFallback);

		///<summary>
		/// Įrengimas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("irengimas")]
		public virtual string Irengimas => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetIrengimas(this, _publishedValueFallback);

		///<summary>
		/// Kambarių skaičius
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("kambariuSkaicius")]
		public virtual int KambariuSkaicius => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetKambariuSkaicius(this, _publishedValueFallback);

		///<summary>
		/// Namo numeris
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("namoNumeris")]
		public virtual string NamoNumeris => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetNamoNumeris(this, _publishedValueFallback);

		///<summary>
		/// Pastato tipas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pastatoTipas")]
		public virtual string PastatoTipas => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetPastatoTipas(this, _publishedValueFallback);

		///<summary>
		/// Plotas (m2)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("plotasM2")]
		public virtual decimal PlotasM2 => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetPlotasM2(this, _publishedValueFallback);

		///<summary>
		/// Renovacijos metai
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("renovacijosMetai")]
		public virtual int RenovacijosMetai => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetRenovacijosMetai(this, _publishedValueFallback);

		///<summary>
		/// Statybos metai
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("statybosMetai")]
		public virtual int StatybosMetai => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetStatybosMetai(this, _publishedValueFallback);

		///<summary>
		/// Viso aukštų
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("visoAukstu")]
		public virtual int VisoAukstu => global::Oppa13.ContentModels.ButoBendriPasirinkimai.GetVisoAukstu(this, _publishedValueFallback);

		///<summary>
		/// Energijos suvartojimo klasė
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("energijosSuvartojimoKlase")]
		public virtual string EnergijosSuvartojimoKlase => global::Oppa13.ContentModels.EnergijosSuvartojimoPasirinkimai.GetEnergijosSuvartojimoKlase(this, _publishedValueFallback);

		///<summary>
		/// Aprašymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymas")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Aprasymas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetAprasymas(this, _publishedValueFallback);

		///<summary>
		/// Aprašymas-EN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymasEN")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AprasymasEN => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetAprasymasEN(this, _publishedValueFallback);

		///<summary>
		/// Aprašymas-RU
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aprasymasRU")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AprasymasRU => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetAprasymasRU(this, _publishedValueFallback);

		///<summary>
		/// Kaina
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("kaina")]
		public virtual int Kaina => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetKaina(this, _publishedValueFallback);

		///<summary>
		/// Automatinis laukas: Šis laukas užsipildo pats - jo keisti nereikia.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaAplankas")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent MediaAplankas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetMediaAplankas(this, _publishedValueFallback);

		///<summary>
		/// Nuotraukos: Pasirinkite aplanką kuriame yra visos skelbimos nuotraukos. Pirma nuotrauka bus naudojama kaip "pagrindinė" objekto nuotrauka skelbimuose
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuotraukos")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Nuotraukos => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetNuotraukos(this, _publishedValueFallback);

		///<summary>
		/// Automatinis laukas: Šis laukas užsipildo pats - jo keisti nereikia.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pagrindineNuotrauka")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent PagrindineNuotrauka => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetPagrindineNuotrauka(this, _publishedValueFallback);

		///<summary>
		/// Top pasiūlymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("populiarus")]
		public virtual bool Populiarus => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetPopuliarus(this, _publishedValueFallback);

		///<summary>
		/// Savininkas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("savininkas")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent Savininkas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetSavininkas(this, _publishedValueFallback);

		///<summary>
		/// Savininko el. paštas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("savininkoElPastas")]
		public virtual string SavininkoElPastas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetSavininkoElPastas(this, _publishedValueFallback);

		///<summary>
		/// Savininko telefonas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("savininkoTelefonas")]
		public virtual string SavininkoTelefonas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetSavininkoTelefonas(this, _publishedValueFallback);

		///<summary>
		/// Savininko vardas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("savininkoVardas")]
		public virtual string SavininkoVardas => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetSavininkoVardas(this, _publishedValueFallback);

		///<summary>
		/// Automatinis laukas: Šis laukas užsipildo pats - jo keisti nereikia.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoUrlName")]
		public virtual string UmbracoUrlName => global::Oppa13.ContentModels.ObjektoAprasymoPasirinkimai.GetUmbracoUrlName(this, _publishedValueFallback);

		///<summary>
		/// Kambario nuomai
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("kambarioNuomai")]
		public virtual bool KambarioNuomai => global::Oppa13.ContentModels.ObjektoTipoPasirinkimai.GetKambarioNuomai(this, _publishedValueFallback);

		///<summary>
		/// Statusas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("objektoStatusas")]
		public virtual string ObjektoStatusas => global::Oppa13.ContentModels.ObjektoTipoPasirinkimai.GetObjektoStatusas(this, _publishedValueFallback);

		///<summary>
		/// Tipas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("objektoTipas")]
		public virtual string ObjektoTipas => global::Oppa13.ContentModels.ObjektoTipoPasirinkimai.GetObjektoTipas(this, _publishedValueFallback);

		///<summary>
		/// Aliolt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("aliolt")]
		public virtual bool Aliolt => global::Oppa13.ContentModels.ObjektoXmlPasirinkimai.GetAliolt(this, _publishedValueFallback);

		///<summary>
		/// Domoplius
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("domoplius")]
		public virtual bool Domoplius => global::Oppa13.ContentModels.ObjektoXmlPasirinkimai.GetDomoplius(this, _publishedValueFallback);

		///<summary>
		/// Realu lt
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("realuLt")]
		public virtual bool RealuLt => global::Oppa13.ContentModels.ObjektoXmlPasirinkimai.GetRealuLt(this, _publishedValueFallback);

		///<summary>
		/// Papildoma įranga
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("papildomaIranga")]
		public virtual global::System.Collections.Generic.List<string> PapildomaIranga => global::Oppa13.ContentModels.PapildomosIrangosPasirinkimai.GetPapildomaIranga(this, _publishedValueFallback);

		///<summary>
		/// Papildomos patalpos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("papildomosPatalpos")]
		public virtual global::System.Collections.Generic.List<string> PapildomosPatalpos => global::Oppa13.ContentModels.PapildomuPatalpuPasirinkimai.GetPapildomosPatalpos(this, _publishedValueFallback);

		///<summary>
		/// Meta antraštė
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaAntraste")]
		public virtual string MetaAntraste => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaAntraste(this, _publishedValueFallback);

		///<summary>
		/// Meta aprašymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaAprasymas")]
		public virtual string MetaAprasymas => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaAprasymas(this, _publishedValueFallback);

		///<summary>
		/// Meta nuotrauka
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaNuotrauka")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent MetaNuotrauka => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaNuotrauka(this, _publishedValueFallback);

		///<summary>
		/// Meta ranktažodžiai
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaRanktazodziai")]
		public virtual string MetaRanktazodziai => global::Oppa13.ContentModels.PuslapioSeopasirinkimai.GetMetaRanktazodziai(this, _publishedValueFallback);

		///<summary>
		/// Šildymas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sildymas")]
		public virtual global::System.Collections.Generic.List<string> Sildymas => global::Oppa13.ContentModels.SildymoPasirinkimai.GetSildymas(this, _publishedValueFallback);

		///<summary>
		/// Adresas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("adresas")]
		public virtual string Adresas => global::Oppa13.ContentModels.VietosPasirinkimai.GetAdresas(this, _publishedValueFallback);

		///<summary>
		/// Ypatybės
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ypatybes")]
		public virtual global::System.Collections.Generic.List<string> Ypatybes => global::Oppa13.ContentModels.YpatybiuPasirinkimai.GetYpatybes(this, _publishedValueFallback);
	}
}
