//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.7.2+fd5b8de
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Oppa13.ContentModels
{
	// Mixin Content Type with alias "trumpalaikesNuomosBendreiPasirinkimai"
	/// <summary>Trumpalaikės nuomos bendrei pasirinkimai</summary>
	public partial interface ITrumpalaikesNuomosBendreiPasirinkimai : IPublishedContent
	{
		/// <summary>Kambarių skaičius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		int KambariuSkaicius { get; }

		/// <summary>Miegamosios vietos</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		int MiegamosiosVietos { get; }

		/// <summary>Namo numeris</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NamoNumeris { get; }

		/// <summary>Plotas (m²)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		int PlotasM2 { get; }

		/// <summary>Tipas</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string Tipas { get; }
	}

	/// <summary>Trumpalaikės nuomos bendrei pasirinkimai</summary>
	[PublishedModel("trumpalaikesNuomosBendreiPasirinkimai")]
	public partial class TrumpalaikesNuomosBendreiPasirinkimai : PublishedContentModel, ITrumpalaikesNuomosBendreiPasirinkimai
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const string ModelTypeAlias = "trumpalaikesNuomosBendreiPasirinkimai";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<TrumpalaikesNuomosBendreiPasirinkimai, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public TrumpalaikesNuomosBendreiPasirinkimai(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Kambarių skaičius
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("kambariuSkaicius")]
		public virtual int KambariuSkaicius => GetKambariuSkaicius(this, _publishedValueFallback);

		/// <summary>Static getter for Kambarių skaičius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static int GetKambariuSkaicius(ITrumpalaikesNuomosBendreiPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "kambariuSkaicius");

		///<summary>
		/// Miegamosios vietos
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("miegamosiosVietos")]
		public virtual int MiegamosiosVietos => GetMiegamosiosVietos(this, _publishedValueFallback);

		/// <summary>Static getter for Miegamosios vietos</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static int GetMiegamosiosVietos(ITrumpalaikesNuomosBendreiPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "miegamosiosVietos");

		///<summary>
		/// Namo numeris
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("namoNumeris")]
		public virtual string NamoNumeris => GetNamoNumeris(this, _publishedValueFallback);

		/// <summary>Static getter for Namo numeris</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNamoNumeris(ITrumpalaikesNuomosBendreiPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "namoNumeris");

		///<summary>
		/// Plotas (m²)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("plotasM2")]
		public virtual int PlotasM2 => GetPlotasM2(this, _publishedValueFallback);

		/// <summary>Static getter for Plotas (m²)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static int GetPlotasM2(ITrumpalaikesNuomosBendreiPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "plotasM2");

		///<summary>
		/// Tipas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tipas")]
		public virtual string Tipas => GetTipas(this, _publishedValueFallback);

		/// <summary>Static getter for Tipas</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTipas(ITrumpalaikesNuomosBendreiPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tipas");
	}
}
