//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.7.2+fd5b8de
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Oppa13.ContentModels
{
	// Mixin Content Type with alias "vandensTelkinoPasirinkimai"
	/// <summary>Vandens telkino pasirinkimai</summary>
	public partial interface IVandensTelkinoPasirinkimai : IPublishedContent
	{
		/// <summary>Ežeras</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		bool Ezeras { get; }

		/// <summary>Iki vandens telkinio (m)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		int IkiVandensTelkinioM { get; }

		/// <summary>Jūra</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		bool Jura { get; }

		/// <summary>Tvenkinys</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		bool Tvenkinys { get; }

		/// <summary>Upė</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		bool Upe { get; }
	}

	/// <summary>Vandens telkino pasirinkimai</summary>
	[PublishedModel("vandensTelkinoPasirinkimai")]
	public partial class VandensTelkinoPasirinkimai : PublishedContentModel, IVandensTelkinoPasirinkimai
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const string ModelTypeAlias = "vandensTelkinoPasirinkimai";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<VandensTelkinoPasirinkimai, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public VandensTelkinoPasirinkimai(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Ežeras
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("ezeras")]
		public virtual bool Ezeras => GetEzeras(this, _publishedValueFallback);

		/// <summary>Static getter for Ežeras</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static bool GetEzeras(IVandensTelkinoPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "ezeras");

		///<summary>
		/// Iki vandens telkinio (m)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("ikiVandensTelkinioM")]
		public virtual int IkiVandensTelkinioM => GetIkiVandensTelkinioM(this, _publishedValueFallback);

		/// <summary>Static getter for Iki vandens telkinio (m)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static int GetIkiVandensTelkinioM(IVandensTelkinoPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "ikiVandensTelkinioM");

		///<summary>
		/// Jūra
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("jura")]
		public virtual bool Jura => GetJura(this, _publishedValueFallback);

		/// <summary>Static getter for Jūra</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static bool GetJura(IVandensTelkinoPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "jura");

		///<summary>
		/// Tvenkinys
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("tvenkinys")]
		public virtual bool Tvenkinys => GetTvenkinys(this, _publishedValueFallback);

		/// <summary>Static getter for Tvenkinys</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static bool GetTvenkinys(IVandensTelkinoPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "tvenkinys");

		///<summary>
		/// Upė
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		[ImplementPropertyType("upe")]
		public virtual bool Upe => GetUpe(this, _publishedValueFallback);

		/// <summary>Static getter for Upė</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.7.2+fd5b8de")]
		public static bool GetUpe(IVandensTelkinoPasirinkimai that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "upe");
	}
}
